# Generated by Django 4.2.4 on 2023-10-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiasGuard1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('education_level', models.CharField(max_length=20)),
                ('cv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='discrimination',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('alert', models.BooleanField(default=False)),
                ('discrimination_name', models.CharField(max_length=20)),
                ('percetage', models.IntegerField(max_length=2)),
                ('recommendation', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_number', models.CharField(max_length=1)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='vacants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.companies')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.description')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('vacant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.vacants')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='discrimination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.discrimination'),
        ),
    ]
