# Generated by Django 4.2.4 on 2023-11-13 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiasGuard1', '0004_alter_qualification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.qualification'),
        ),
    ]
