# Generated by Django 4.2.4 on 2023-11-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
        ('BiasGuard1', '0005_alter_offer_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analitica.companies'),
        ),
        migrations.AddField(
            model_name='offer',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NewOffer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiasGuard1.offer')),
            ],
        ),
    ]
