# Generated by Django 4.2.4 on 2023-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiasGuard1', '0006_offer_company_offer_state_newoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='qualification',
        ),
        migrations.AddField(
            model_name='offer',
            name='qualification',
            field=models.ManyToManyField(to='BiasGuard1.qualification'),
        ),
    ]
